[workspace.package]
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = [
    "compile-time",
    "executor",
    "executor/pb/c",
    "executor/pb/rust",
    "executor/protobuf-c/wasm",
    "runners",
    "strace",
    "wasi",
    "wasi-sdk/build",
    "witx",
]

[workspace.dependencies]
strace.path = "strace"
wasi-sdk.path = "wasi-sdk/build"
wazzi-compile-time.path = "compile-time"
wazzi-executor.path = "executor"
wazzi-executor-pb-c.path = "executor/pb/c"
wazzi-executor-pb-rust.path = "executor/pb/rust"
wazzi-executor-protobuf-c-wasm.path = "executor/protobuf-c/wasm"
wazzi-runners.path = "runners"
wazzi-snapshot.path = "snapshot"
wazzi-wasi.path = "wasi"
wazzi-witx.path = "witx"

arbitrary = "1"
cc = "*"
color-eyre = "0.6"
nom = "7"
once_cell = "1"
petgraph = "0.6"
protobuf = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "1"
tracing = "0.1"

[package]
name = "wazzi"
version = "0.1.0"
edition.workspace = true

[dependencies]
wazzi-executor.workspace = true
wazzi-runners.workspace = true
wazzi-wasi.workspace = true
wazzi-witx.workspace = true

serde_json.workspace = true
