[package]
name = "wazzi-spec-evaluator"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gcollections = "1"
intervallum.workspace = true
num-bigint = "0.4"
num-traits = "*"

[dev-dependencies]
arbitrary.workspace = true
rand.workspace = true
