[package]
name = "wazzi-store"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
wazzi-wasi-component-model.workspace = true

eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
