[package]
name = "strace"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
nix.workspace = true
nom.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile.workspace = true
