[package]
name = "wazzi-executor-pb-rust"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
protobuf.workspace = true

[build-dependencies]
wazzi-compile-time.workspace = true
wazzi-executor-protobuf.workspace = true
protobuf-codegen = "*"
