[package]
name = "wazzi-dyn-fuzzer"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
wazzi-dyn-spec.workspace = true
wazzi-runners.workspace = true
wazzi-store.workspace = true

color-eyre.workspace = true
eyre.workspace = true
