[package]
name = "wazzi-executor-pb"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
wazzi-executor-protobuf-c-wasm.workspace = true

[build-dependencies]
wazzi-executor-pb-c.workspace = true
