/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: executor-pb/wazzi-executor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "executor-pb/wazzi-executor.pb-c.h"
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   call__init
                     (Call         *message)
{
  static const Call init_value = CALL__INIT;
  *message = init_value;
}
size_t call__get_packed_size
                     (const Call *message)
{
  assert(message->base.descriptor == &call__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t call__pack
                     (const Call *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &call__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t call__pack_to_buffer
                     (const Call *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &call__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Call *
       call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Call *)
     protobuf_c_message_unpack (&call__descriptor,
                                allocator, len, data);
}
void   call__free_unpacked
                     (Call *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &call__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request__field_descriptors[1] =
{
  {
    "call",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, which_case),
    offsetof(Request, call),
    &call__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  0,   /* field[0] = call */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  1,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor call__field_descriptors[1] =
{
  {
    "func",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Call, func),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned call__field_indices_by_name[] = {
  0,   /* field[0] = func */
};
static const ProtobufCIntRange call__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor call__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Call",
  "Call",
  "Call",
  "",
  sizeof(Call),
  1,
  call__field_descriptors,
  call__field_indices_by_name,
  1,  call__number_ranges,
  (ProtobufCMessageInit) call__init,
  NULL,NULL,NULL    /* reserved[123] */
};
