/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: executor-pb/wazzi-executor.proto */

#ifndef PROTOBUF_C_executor_2dpb_2fwazzi_2dexecutor_2eproto__INCLUDED
#define PROTOBUF_C_executor_2dpb_2fwazzi_2dexecutor_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Request Request;
typedef struct Call Call;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  REQUEST__WHICH__NOT_SET = 0,
  REQUEST__WHICH_CALL = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(REQUEST__WHICH__CASE)
} Request__WhichCase;

struct  Request
{
  ProtobufCMessage base;
  Request__WhichCase which_case;
  union {
    Call *call;
  };
};
#define REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request__descriptor) \
, REQUEST__WHICH__NOT_SET, {0} }


struct  Call
{
  ProtobufCMessage base;
  char *func;
};
#define CALL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&call__descriptor) \
, (char *)protobuf_c_empty_string }


/* Request methods */
void   request__init
                     (Request         *message);
size_t request__get_packed_size
                     (const Request   *message);
size_t request__pack
                     (const Request   *message,
                      uint8_t             *out);
size_t request__pack_to_buffer
                     (const Request   *message,
                      ProtobufCBuffer     *buffer);
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator);
/* Call methods */
void   call__init
                     (Call         *message);
size_t call__get_packed_size
                     (const Call   *message);
size_t call__pack
                     (const Call   *message,
                      uint8_t             *out);
size_t call__pack_to_buffer
                     (const Call   *message,
                      ProtobufCBuffer     *buffer);
Call *
       call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   call__free_unpacked
                     (Call *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Request_Closure)
                 (const Request *message,
                  void *closure_data);
typedef void (*Call_Closure)
                 (const Call *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor request__descriptor;
extern const ProtobufCMessageDescriptor call__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_executor_2dpb_2fwazzi_2dexecutor_2eproto__INCLUDED */
