[package]
name = "wazzi-snapshot"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
