[package]
name = "wazzi-spec-constraint"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gcollections.workspace = true
intervallum.workspace = true
num-bigint.workspace = true
num-traits = "*"
thiserror.workspace = true

[dev-dependencies]
