[package]
name = "wazzi-spec"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
eyre.workspace = true
nom.workspace = true
nom_locate.workspace = true
nom-supreme.workspace = true
petgraph.workspace = true
thiserror.workspace = true
