[package]
name = "wazzi-executor"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
build = "build.rs"

[build-dependencies]
wazzi-executor-capnp-c.workspace = true

[dependencies]
wazzi-executor-capnp.workspace = true
wazzi-runners.workspace = true

capnp.workspace = true
