[package]
name = "wazzi-dyn-spec"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
wazzi-spec.workspace = true

arbitrary.workspace = true
thiserror.workspace = true

[dev-dependencies]
nom.workspace = true
nom-supreme.workspace = true
