[package]
name = "wazzi-runners"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
eyre.workspace = true
tera.workspace = true
tracing.workspace = true

[dev-dependencies]
