WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

prog_final = _{ SOI ~ stmt* ~ EOI }

stmt =
 _{ record_field_set
  }

expr =
 _{ u64_const
  | variant_const
  }

id = @{ "$" ~ (ASCII_ALPHANUMERIC | "." | "-" | "_")+ }
number = @{ "-"? ~ ASCII_DIGIT+ }

record_field_set =
  { "(" ~ "@record.field.set"
  ~ "(" ~ "result" ~ id ~ ")"
  ~ id ~ expr ~ ")"
  }

u64_const = { "(" ~ "@u64.const" ~ number ~ ")" }

variant_const =
  { "(" ~ "@variant.const"
  ~ id
  ~ id
  ~ ")"
  }
