[package]
name = "wazzi-executor-pb-c"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]

[build-dependencies]
wazzi-compile-time.workspace = true
wazzi-executor-protobuf-c.workspace = true
